RegisterNetEvent("PC:SpawnServer")
AddEventHandler("PC:SpawnServer", function()
    print("Spawning Christine for player with id ", source)
    TriggerClientEvent("PC:SpawnClient", source)
end)

RegisterNetEvent("PC:DespawnServer")
AddEventHandler("PC:DespawnServer", function(Christine, Driver)
    print("Despawning Christine for player with id ", source)
    TriggerClientEvent("PC:DespawnClient", source)
end)
